version: 2
project_name: gitm

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X github.com/alexDouze/gitm/cmd.Version={{.Version}} -X github.com/alexDouze/gitm/cmd.Commit={{.Commit}} -X github.com/alexDouze/gitm/cmd.Date={{.Date}}
    binary: gitm
    main: .

archives:
  - id: default
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- .Arch }}
    
    formats:
    - binary
    files:
      - README.md
      - LICENSE*

checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - '^chore:'
      - Merge pull request
      - Merge branch

release:
  github:
    owner: alexDouze
    name: git-manager
  prerelease: auto
  draft: false
  name_template: "v{{ .Version }}"
